### ISSUE TITLE
DoT/DoH support

### ISSUE THREAD

**Issue by dimqua** [nadoo/glider#141]
It'd nice to have a possibility to use the program as an encrypted DNS (DNS over TLS, DNS over HTTPS) client, and not just a forwarder to other DNS servers.

This is exactly how it's implemented in [Clash](https://github.com/Dreamacro/clash), for example.

**Comment by nadoo** [comment]
glider supports dns over proxy, I think it's more suitable for our usage, because we can get the resolved ip addresses which are close to our proxies.

**Comment by sergeevabc** [comment]
+1 for an option to specify DoH, because DNS over proxy fails when it's rule-based.

For example, you specify to proxy all `com` domains and then go to https://browserleaks.com/dns which internally polls some `org` domains.

So, `browserleaks.com` is proxified, but also you have a detected DNS leak. This would not have happened if a DoH server had been specified that resolves any domains.
