### ISSUE TITLE
How can I write V2RAY with a disguised website?

### ISSUE THREAD

**Issue by xinming2008** [nadoo/glider#170]
地址：sh.bit.co
端口：9130
用户id：e3368f62-d28d-4b03-879a-ec98f529d
额外id：2
加密方式：auto
传输协议：ws
伪装类型：none
伪装域名：www.baidu.com
路径：/cctv/hd3u8
底层传输安全：无
我是这样写的
forward=ws://www.baidu.com:80/cctv/hd3u8,vmess://e3368f62-d28d-4b03-879a-ec98f529d@sh.bit.co:9130?alterID=2
看日志显示没有链接成功，请问大师该如何写呢？

**Comment by nadoo** [comment]
Please try:
```
forward=ws://sh.bit.co:9130/cctv/hd3u8?host=www.baidu.com,vmess://e3368f62-d28d-4b03-879a-ec98f529d@?alterID=2
```

**Comment by xinming2008** [comment]
Thank you very much!I'm sucessful

**Comment by qqqqqqrrrrhh123a** [comment]
大佬帮我看看这个问题 https://github.com/nadoo/glider/issues/270

**Comment by xtangliang** [comment]
@nadoo It doesnt work, could u plz helping me to check these out. I tried many diffrent ways.
way 1 : not use fake host, it works
way 2: try to use fake host like you mention above, it doesnt work
way 3: try to use serverName instead of host, it doesnt work
way 4: try to use tls://+ws:// instead of wss://, it doesnt work
way 5: try to add , it doesnt work
way 6: try to add echo host:port in the end, it doesnt work

-------------------------
there are my sentences:

AAA: Vless Server domian
BBB: CloudFlare CDN domain
CCC: Fake IP


glider -verbose -listen socks5://:11111 -forward wss://BBB:443,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------host + @ in the end
glider -verbose -listen socks5://:11111 -forward wss://BBB:443?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward wss://CCC:443?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------serverName + @ in the end
glider -verbose -listen socks5://:11111 -forward wss://CCC:443?serverName=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward wss://BBB:443?serverName=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------try tls://+ws:// > wss://
glider -verbose -listen socks5://:11111 -forward tls://BBB:443,ws://@/?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@
			
glider -verbose -listen socks5://:11111 -forward tls://CCC:443,ws://@/?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@
			
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?serverName=CCC,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@
			
glider -verbose -listen socks5://:11111 -forward tls://CCC:443?serverName=BBB,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@

--------host + skipVerify + @ in the end
glider -verbose -listen socks5://:11111 -forward wss://BBB:443?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward wss://CCC:443?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------serverName + skipVerify + @ in the end
glider -verbose -listen socks5://:11111 -forward wss://CCC:443?serverName=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward wss://BBB:443?serverName=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------host + skipVerify + AAA in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true,ws://@/?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@AAA.com:443

glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true,ws://@/?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@AAA.com:443
--------serverName + skipVerify + AAA in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true&serverName=CCC,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@AAA.com:443

glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true&serverName=BBB,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@AAA.com:443
--------host + skipVerify + BBB in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true,ws://@/?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443
			
glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true,ws://@/?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443
--------serverName + skipVerify + BBB in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true&serverName=CCC,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443
--------host + skipVerify + CCC in the end
glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true&serverName=BBB,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443
--------serverName + skipVerify + CCC in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true&serverName=CCC,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@CCC:443

glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true&serverName=BBB,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@CCC:443

**Comment by xtangliang** [comment]
2021/10/16 16:52:25 server.go:82: [socks5] 127.0.0.1:61393 <-> ip-api.com:80 via CCC:443, error in dial: x509: cannot validate certificate for CCC because it doesn't contain any IP SANs
2021/10/16 16:52:25 server.go:82: [socks5] 127.0.0.1:61397 <-> www.ip-api.com:443 via CCC:443, error in dial: x509: cannot validate certificate for CCC because it doesn't contain any IP SANs
