### ISSUE TITLE
Questions about the use of redir listener

### ISSUE THREAD

**Issue by p0we7** [nadoo/glider#182]
I'm using the glider redir listener, and I set up iptables and ipset, but I can't listen to port 53 again because it's already occupied by another program on my system. I also know that redir mode requires dns parsing to get the ip address, adding ip to the ipset list, and using iptables to redirect the connection to the redir listener's port in the next http connection.

I've tested that it is possible to manually fill in the `rule` file with the resolved ip (e.g. `ip=1.1.1.1`), and then redirect the http connection to the redir listener without using glider's dns resolver.

The domain I need to proxy is `api.telegram.com`, and I'm not sure if the ip address of this domain is updated often, so is there a way for glider to automatically update the IP address of the domain and add it to the ipset list.

----
following is my test config

```
# glider.conf

verbose=True

listen=redir://:1088
 
rulefile=tg.rule
```

```
# tg.rule

forward=ss://rc4-md5@example.com:4444

ipset=glider

domain=api.telegram.org
ip=149.154.167.220
```

```
# /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
149.154.167.220 api.telegram.org
```

**Comment by nadoo** [comment]
Currently I use glider as my only dns server in my network, glider listen's on :53 and /etc/resolv.conf was set to 127.0.0.1, so all dns requests will received by glider and the domain-ip rule will be updated.

In your environment, if you use dnsmasq (or any other dns server supports ipset) as your primary dns server, you can try:
https://github.com/nadoo/glider/tree/master/config/examples/8.transparent_proxy_with_dnsmasq
to see whether it meet your requirements.

Otherwise, I'm considering forcing all requests to be resolved by the builtin dns server in the future version, then we can update the domain-ip rule automatically without the requirement of listening on :53.

**Comment by nadoo** [comment]
Sorry I made a mistake in the previous comment, as we use redir listener, we can only get the ip address of the destination, so we can't update the domain-ip map here.

The best solution is still:
```
In your environment, if you use dnsmasq (or any other dns server supports ipset) as your primary dns server, you can try:
https://github.com/nadoo/glider/tree/master/config/examples/8.transparent_proxy_with_dnsmasq
to see whether it meet your requirements.
```
