### ISSUE TITLE
[Question] Does it make sense to run dns separately in redir&ipset scenario

### ISSUE THREAD

**Issue by ffftwo** [nadoo/glider#210]
I'm curious about the difference in performance, according to [this](https://github.com/nadoo/glider/blob/master/config/examples/9.transparent_proxy_without_dnsmasq/README.md#when-client-requesting-to-access-httpexample1com-in-officerule-the-whole-process), there will be two lookup action, I think running dns separately will reduce the lookup times, but not so sure, and if it dose, is it worth running that way due to the impact of performance?

>    upstream dns server choice: glider will lookup it's rule config and find out the dns server to use for this domain(matched "example1.com" in office.rule, so 208.67.222.222:53 will be chosen)

>    glider finds the ip in office rule, and then choose a forwarder in office.rule to complete the request.

## All-In-One
```shell
glider -config aio.conf
```
```ini
#aio.conf
dns=:53
dnsserver=233.5.5.5:53
listen=redir://:1081
rulefile=dns-proxy.rule

#dns-proxy.rule
forward=ss://method:pass@host:port
dnsserver=1.1.1.1:53
ipset=glider
domain=some.domain.names
```
---
### proxy
```shell
glider -forward ss://method:pass@host:port -listen socks5://127.0.0.1:1080 -listen redir://:1081
```
### dns
```shell
glider -config dns.conf
```
```ini
#dns.conf
dns=:53
dnsserver=233.5.5.5:53
rulefile=dns-proxy.rule

#dns-proxy.rule
forward=socks5://127.0.0.1:1080
dnsserver=1.1.1.1:53
ipset=glider
domain=some.domain.names
```

**Comment by nadoo** [comment]
The dns server implementation of glider may not as sufficient as dnsmasq(because dnsmasq was written in C).

But, the answer to your question depends on your requirements and the hardware of your gateway box.

In my environment, glider runs as transparent proxy without dnsmasq(like your all in one config) on a Linux gateway with Debian 10 os, serving 200+ clients(pc,phone) without any problem, and the hardware of that Linux gateway is: N3710,2GB ram,16GB ssd. The system load and cpu usage is not high.

Actually, that's why I wrote glider, you can test both 2 modes and see which is more suitable. All in one mode is more flexible because glider's ipset manager supports not only domain, but also ip and cidr.

**Comment by nadoo** [comment]
after rereading your config, I find that you don't use dnsmasq at all, then I advise you to use the all in one mode, as I always use.

**Comment by ffftwo** [comment]
> after rereading your config, I find that you don't use dnsmasq at all, then I advise you to use the all in one mode, as I always use.

I see, thank you for your advice.
