### ISSUE TITLE
Multiple Listeners Issue

### ISSUE THREAD

**Issue by w3rkzeug** [nadoo/glider#259]
Hello,
First of all thanks for the efforts in this project, 
I'm trying to launch multiple listeners to forwarders (one-to-one : e.g. `listener->forwarder` ) using the config just like i would do with the cli several times : 
See the example that i want to replicate using 1 config file:

`./glider  -verbose -listen :35001 -forward socks5://10.99.99.1:10000`
`./glider  -verbose -listen :35002 -forward socks5://10.99.99.2:10000`
`./glider  -verbose -listen :35003 -forward socks5://10.99.99.3:10000
....& so on`

Config: 
![image](https://user-images.githubusercontent.com/40423351/121162077-42e55300-c856-11eb-8e7e-ac56e9f062bd.png)

Log File:
![image](https://user-images.githubusercontent.com/40423351/121161972-28ab7500-c856-11eb-807d-3d5d5fa57df9.png)

Running `./glider`,the ports are opening:

![image](https://user-images.githubusercontent.com/40423351/121162798-e898c200-c856-11eb-84fc-0e4c5d2bdf38.png)

, but using the config mode looks like glider is splitting the requests between the forwarders, not considering the order/mapping.

I'm accessing f.e. `:35000` which should forward me to `10.99.99.2:10000` only, but it sends the packets through any of the availabale forwarders within the config .

Any idea/suggestion how to achieve this goal with glider in config file mode ?
Many Thanks.

**Comment by nadoo** [comment]
Hi @EmpireOneDevs , glider has builtin load balance feature, you should use multiple config files instead.

**Comment by EmpireOneDevs** [comment]
Hi @nadoo ,
I did try the following:
`# include=/configs/35000.conf
# include=/configs/35001.conf
# include=/configs/35002.conf
# include=/configs/35003.conf`

& each has the contents as follows:
/configs/35000.conf
`# # Forward to DM
listen=:35000
forward=socks5://10.99.99.2:10000`

/configs/35001.conf
`# # Forward to GV
listen=:35001
forward=socks5://10.99.99.2:10000`
`etc...`

But i get load balanced as well.... actually i thought having these in a DB so that this could be easily managed from a GUI afterwards...
Thanks

**Comment by nadoo** [comment]
just run multiple instances, like: 
1. `glider -config 35000.conf`
2. `glider -config 35001.conf`
3. `glider -config 35002.conf`

**Comment by EmpireOneDevs** [comment]
Got it ,
Can you suggest a way to launch/kill these programatically ?
Thanks

**Comment by nadoo** [comment]
Sorry, I have no experience in this field, maybe you can use supervisord with a service group config?
