### ISSUE TITLE
Rotating Proxies

### ISSUE THREAD

**Issue by mxschmitt** [nadoo/glider#42]
Hello,

it is possible, that i provide glider a few http proxies and it switches e.g. every minute or every request the proxy?

Best regards

Max

**Comment by nadoo** [comment]
Yes, it's possible, create a config file with multiple forwarders:

`glider.conf`
```bash
listen=:8443
forward=http://proxyip1:port
forward=http://proxyip2:port
forward=socks5://proxyip3:port

strategy=rr
checkwebsite=www.apple.com
checkduration=30
```

start glider with: `glider -cnofig glider.conf`

set your browser's proxy to ip:8443, then glider will forward requests via forwarders in round robin mode, see https://github.com/nadoo/glider/blob/master/config/glider.conf.example for more details.

**Comment by mxschmitt** [comment]
I also thought so 👍 

But the strange part here is, that some proxies of me might not work with glider. Glider will log the following:

```
31.7.2018 13:23:482018/07/31 11:23:48 [check] XX.XX.XX.XX:4145 -> www.apple.com:80, set to DISABLED. error in dial: [http] can not connect remote address: www.apple.com:80. error code: 502
```

from this function in the bottom:

https://github.com/nadoo/glider/blob/4781e7b4725c230a6d844a3d5b29e629dcfceb0b/proxy/http/http.go#L223-L257

But when I try the exact same proxy via curl e.g. it works:
```
 # curl -x "http://XX.XX.XX.XX:4145" 'http://apple.com' -v
* Rebuilt URL to: http://apple.com/
*   Trying XX.XX.XX.XX...
* TCP_NODELAY set
* Connected to XX.XX.XX.XX (XX.XX.XX.XX) port 4145 (#0)
> GET http://apple.com/ HTTP/1.1
> Host: apple.com
> User-Agent: curl/7.61.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 301 Moved Permanently
< Server: Apache
< Date: Tue, 31 Jul 2018 11:25:32 GMT
< Location: https://www.apple.com/
< Content-Type: text/html
< X-Cache: MISS from localhost.localdomain
< X-Cache-Lookup: MISS from localhost.localdomain:2999
< Transfer-Encoding: chunked
< Via: 1.1 localhost.localdomain (squid/3.5.27)
< Connection: keep-alive
<
* Connection #0 to host XX.XX.XX.XX left intact
```

**Comment by mxschmitt** [comment]
I think that's squid proxy servers (version 3.5.27).

It also does not work with the changes of you.

**Comment by mxschmitt** [comment]
Hm....
````
~/go/src/github.com/nadoo/glider # curl -x "http://XX.XX.XX.XX:4145" www.apple.com -v -p
* Rebuilt URL to: www.apple.com/
*   Trying XX.XX.XX.XX...
* TCP_NODELAY set
* Connected to XX.XX.XX.XX (XX.XX.XX.XX) port 4145 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.apple.com:80
> CONNECT www.apple.com:80 HTTP/1.1
> Host: www.apple.com:80
> User-Agent: curl/7.61.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 502 Bad Gateway
< Server: squid/3.5.27
< Mime-Version: 1.0
< Date: Tue, 31 Jul 2018 18:35:01 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 1
< X-Squid-Error: ERR_CONNECT_FAIL 0
< Vary: Accept-Language
< Content-Language: en
<
* Received HTTP code 502 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 502 from proxy after CONNECT
```

maybe the proxies are broken? idk.

**Comment by nadoo** [comment]
Hi @mxschmitt , in your case, the upstream squid server only support 2 types of requests:

1. tunnel: using http `CONNECT` to establish a `tcp tunnel` to the destination address, and this **only allowed to access the port 443**.
2. http proxy: using http `GET` to send request in http header, and this **only allowed to access http sites**.

so in your situation, the best result we can achieve is that glider runs as http proxy client, and can access both http and https websites, but no other tcp services, right?

when using glider as a http proxy server, it support both http requests and tcp tunnel mode(using CONNECT method).

when glider acts as a http proxy client, it always tries to use http `CONNECT` to establish a tcp tunnel, because only tcp tunnel can support general usage, any protocols run on tcp can run on a tcp tunnel, like dns, http, https, ssh etc.

as more and more websites migrated to http2.0(https), I intend to support http `CONNECT` only, so we can simply use `dialer.Dial(addr)` to connect addr via upstream proxies whitout the need for diving into application layer protocols.

**Comment by mxschmitt** [comment]
Oh okay. Thank you for the great support!

**Comment by bogisi** [comment]
Is there any way to solve this problem?
i am having problems forwarding with brightdata.com - luminati.io:

```
client.go:68: [http] 'CONNECT' to ports other than 443 are not allowed by proxy zproxy.lum-superproxy.io:22225
server.go:89: [http] 127.0.0.1:51154 <-> www.google.com:80 [c] via zproxy.lum-superproxy.io:22225, error in dial: [http] can not connect remote address: www.google.com:80. error code: 403
```
