### ISSUE TITLE
Request: DNS over TCP

### ISSUE THREAD

**Issue by platkaw** [nadoo/glider#49]
Instead of using an upstream DNS via UDP protocol it will use DNS over TCP, something like 

-dnsserver=8.8.8.8:53:tcp
-dnsserver=8.8.8.8:53:udp

**Comment by nadoo** [comment]
From v0.6.5, when client requests glider's builtin dns server in udp and there's no forwarder specified, glider will query upstream dns server in udp, otherwise, it will use tcp.

It's a good suggestion to add the config to specify the protocol used to request upstream dns servers, but some protocols do not support udp, e.g. if we query upstream dns server in udp and a http forwarder specified, there will be a problem. 

I'll look into it later, hope to find a good way to implement this.

**Comment by nadoo** [comment]
I intend to add a new config `dnsovertcp`, which support 2 modes:
- `auto`: when glider received udp dns request and there's no forwarder specified, use udp to query upstream dns servers, otherwise, use tcp;
- `always`: always use tcp to query upstream dns servers.

Do you think whether it will match your requirement?

**Comment by platkaw** [comment]
Tried your latest commit and it works fine without issues, Thank you for adding the feature. Would it be also possible to add a feature that if there are multiple upstream dns forwarders set, there is an option to send the query to all upstream dns then whatever the first result will be returned. The same with dnsmasq --all-servers option, and combining it with dnsalwaystcp then this would be perfect.

**Comment by nadoo** [comment]
Hi @platkaw , resolving a domain name fast does not mean connect the resolved ip fast, as glider has builtin dns cache, is it really necessary to add this feature?

**Comment by platkaw** [comment]
Hi @nadoo , it would benefit for users who have problematic routing on their ISPs. In my case there are times that 1.1.1.1 is faster than 8.8.8.8 and other DNS servers vice versa, which sometimes the other keep on timing out. If glider would query on all the available DNS servers then the slowness, timeouts will be prevented.

**Comment by xlighting2017** [comment]
@platkaw for "timeout", do you mean "A: timeout when query DNS" or "B: query DNS and timeout when connect to the resolved IP"?

if I understand correctly from the source code:
if it's the case A,  you can simply set dnstimeout=1 in config, and glider will  "query the first DNS, if error/timeout, go next", 
if it's the case B, I don't think "query All DNS at same time" will help improve the situation, because as @nadoo said: "the faster DNS reply" has no relevance to "the faster connection to resolved IP"

IMHO, if your problem is "random timeout when querying DNS", then add such function in glider is merely a workaround, you should try improve the network, not workaround it in a Layer-7 App/Proxy

Could you share some of the config/logs when your problem happens?

**Comment by platkaw** [comment]
It doesn't always timeout. My issue is there are times the secondary DNS server is faster than my primary. Yes adding dnstimeout as low as possible would simply use the next DNS after that duration. However if glider does query all the DNS servers at the same time, it will return the value as fast as possible without waiting for the "timeout" for the first DNS entry.

What I am doing right now, is run multiple glider process listening to different ports, having different DNS entry and set to dnsmasq as forwarders with all-servers turned on.
